In [1]:
import numpy as np

In [3]:
empty_array=np.empty(shape=(2,3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
array_0s=np.zeros(shape=(2,3),dtype='int32')
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [9]:
array_1s=np.ones(shape=(2,3))
array_1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
array_full=np.full(shape=(2,3),fill_value=2)
array_full

array([[2, 2, 2],
       [2, 2, 2]])