In [1]:
import numpy as np

In [3]:
#returns a range object
range(30)

range(0, 30)

In [5]:
#converting the range object to a list 
list(range(30))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [7]:
arange_array=np.arange(20)

In [9]:
arange_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
arange_array=np.arange(stop=20)
arange_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
arange_array=np.arange(start=0,stop=20)
arange_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
arange_array=np.arange(start=0,stop=20,step=2)
arange_array


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
arange_array=np.arange(start=0,stop=20,step=2.5)
arange_array

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

In [27]:
#The step becomes of no 2 as the function assumes we want the same no of values as in the previous response
arange_array=np.arange(start=0,stop=20,step=2.5,dtype='int32')

In [29]:
arange_array

array([ 0,  2,  4,  6,  8, 10, 12, 14], dtype=int32)