In [1]:
import numpy as np
company_data_numeric=np.loadtxt("Lending-company-Numeric.csv",delimiter=",")
company_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [3]:
#returns the co-ordinates of the comcompany_data_numeric array in row , column form 
np.argwhere(company_data_numeric)

array([[   0,    0],
       [   0,    1],
       [   0,    2],
       ...,
       [1042,    3],
       [1042,    4],
       [1042,    5]])

In [5]:
#It can also be used with conditionals
np.argwhere(company_data_numeric>1000)

array([[   0,    0],
       [   0,    3],
       [   0,    4],
       ...,
       [1042,    3],
       [1042,    4],
       [1042,    5]])

In [9]:
np.argwhere(company_data_numeric<1000)

array([[   0,    1],
       [   0,    2],
       [   1,    1],
       ...,
       [1041,    2],
       [1042,    1],
       [1042,    2]])

In [11]:
np.argwhere(company_data_numeric%2==0)

array([[   0,    0],
       [   0,    1],
       [   1,    0],
       ...,
       [1042,    0],
       [1042,    1],
       [1042,    5]])

In [13]:
company_data_numeric_NAN=np.genfromtxt("Lending-company-Numeric-NAN.csv",delimiter=";")
company_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [17]:
#Returns the co-ordinates where the nan values are present 
np.argwhere(np.isnan(company_data_numeric_NAN))

array([[  11,    3],
       [  15,    3],
       [  27,    3],
       [  58,    3],
       [  60,    4],
       [  85,    4],
       [ 117,    5],
       [ 152,    1],
       [ 152,    2],
       [ 152,    4],
       [ 172,    1],
       [ 175,    1],
       [ 175,    2],
       [ 176,    3],
       [ 177,    4],
       [ 178,    5],
       [ 211,    3],
       [ 229,    0],
       [ 230,    1],
       [ 237,    1],
       [ 247,    3],
       [ 251,    5],
       [ 252,    4],
       [ 258,    1],
       [ 260,    3],
       [ 262,    4],
       [ 271,    5],
       [ 272,    4],
       [ 284,    2],
       [ 284,    3],
       [ 297,    1],
       [ 297,    2],
       [ 300,    3],
       [ 315,    3],
       [ 315,    5],
       [ 327,    4],
       [ 336,    4],
       [ 343,    0],
       [ 344,    2],
       [ 346,    2],
       [ 363,    3],
       [ 375,    3],
       [ 377,    2],
       [ 398,    5],
       [ 416,    4],
       [ 428,    0],
       [ 432,    1],
       [ 433,

In [19]:
company_data_numeric_NAN[11]

array([ 2000.,    50.,   365.,    nan,  4190., 10790.])

In [21]:
company_data_numeric_NAN[15]

array([ 2000.,    40.,   365.,    nan,  4801., 15001.])

In [29]:
#For every value (array_index) in the nan values we replace that value at row and column (see block 17) by 0
for array_index in np.argwhere(np.isnan(company_data_numeric_NAN)):
    company_data_numeric_NAN[array_index[0],array_index[1]]=0

In [31]:
#Now we have 0 instead of the NAN
company_data_numeric_NAN[11]

array([ 2000.,    50.,   365.,     0.,  4190., 10790.])

In [33]:
company_data_numeric_NAN[15]

array([ 2000.,    40.,   365.,     0.,  4801., 15001.])

In [35]:
#No values are nan in the company_data_numeric_NAN array after replacement
np.isnan(company_data_numeric_NAN).sum()

np.int64(0)