In [1]:
import numpy as np

In [17]:
list_a=[[1,2,3],[4,5,6]]
list_a

[[1, 2, 3], [4, 5, 6]]

In [19]:
array_a=np.array(list_a)
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
type(list_a)

list

In [23]:
type(array_a)

numpy.ndarray

In [25]:
array_a.shape

(2, 3)

In [29]:
#Lists dont have shape 
list_a.shape

AttributeError: 'list' object has no attribute 'shape'

In [31]:
#tells us how many inner lists are contained in the nested lists
len(list_a)

2

In [33]:
#if we need to find the no of elements in the first list we need to use index 0
len(list_a[0])

3

In [ ]:
#similarly if we need to find the no of elements in the second list we need to use index 1
len(list_a[1])

In [37]:
array_b=array_a[0]+array_a[1]
list_b=list_a[0]+list_a[1]


In [39]:
#The arrays are added to give us the added output 
array_b

array([5, 7, 9])

In [41]:
#The lists are concatenated
list_b

[1, 2, 3, 4, 5, 6]

In [43]:
np.sqrt(array_b)

array([2.23606798, 2.64575131, 3.        ])