In [3]:
import numpy as np
matrix_a=np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_a

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [5]:
np.cov(matrix_a)

array([[ 1.5, -2. ,  2. ],
       [-2. ,  7.7, -7. ],
       [ 2. , -7. ,  8.5]])

In [13]:
#numpy has corrcoef as the functionreturns the correlation array
np.corrcoef(matrix_a)

array([[ 1.        , -0.58848989,  0.56011203],
       [-0.58848989,  1.        , -0.8652532 ],
       [ 0.56011203, -0.8652532 ,  1.        ]])