In [1]:
import numpy as np


In [5]:
array_1=np.array([[1,2,3],[4,5,6]])
print(array_1)

[[1 2 3]
 [4 5 6]]


In [9]:
array_1=np.array([[1,2,3],[4,5,6]],dtype='int64')
print(array_1)

[[1 2 3]
 [4 5 6]]


In [11]:
array_1=np.array([[1,2,3],[4,5,6]],dtype='float64')
print(array_1)

[[1. 2. 3.]
 [4. 5. 6.]]


In [13]:
array_1=np.array([[1,2,3],[4,5,6]],dtype='complex128')
print(array_1)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [15]:
array_1=np.array([[1,2,3],[4,5,6]],dtype='str')
print(array_1)

[['1' '2' '3']
 ['4' '5' '6']]
