In [3]:
import numpy as np
company_data_numeric=np.loadtxt("Lending-company-Numeric.csv",delimiter=",")
company_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [5]:
#Removed the first element of the array 
np.delete(company_data_numeric,0)

array([   40.,   365.,  3121., ...,  4601.,  4601., 16600.])

In [7]:
#deleted the first column of the array 
np.delete(company_data_numeric,0,axis=0)

array([[ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [11]:
#deleted the first row of the array 
np.delete(company_data_numeric,0,axis=1)

array([[   40.,   365.,  3121.,  4241., 13621.],
       [   40.,   365.,  3061.,  4171., 15041.],
       [   40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  4201.,  5001., 16600.],
       [   40.,   365.,  2080.,  3320., 15600.],
       [   40.,   365.,  4601.,  4601., 16600.]])

In [13]:
#deleted the first second and third rows of the arrays
np.delete(company_data_numeric,(0,1,2),axis=1)

array([[ 3121.,  4241., 13621.],
       [ 3061.,  4171., 15041.],
       [ 2160.,  3280., 15340.],
       ...,
       [ 4201.,  5001., 16600.],
       [ 2080.,  3320., 15600.],
       [ 4601.,  4601., 16600.]])

In [15]:
#deleted the the second third and the last columns of the deleted first second and third rows of the original array
np.delete(np.delete(company_data_numeric,(0,1,2),axis=1),[1,2,-1,],axis=0)

array([[ 3121.,  4241., 13621.],
       [ 3041.,  4241., 15321.],
       [ 3470.,  4820., 13720.],
       ...,
       [ 4240.,  5440., 16600.],
       [ 4201.,  5001., 16600.],
       [ 2080.,  3320., 15600.]])

In [17]:
#the original array doesn't get affected by these operations
company_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])