In [1]:
import numpy as np

In [3]:
array_a=np.array([[1,2,3],[4,5,6]])
print(array_a)


[[1 2 3]
 [4 5 6]]


In [7]:
array_b=np.array([9,3,2])
print(array_b)

[9 3 2]


In [29]:
#addition of lists concatenate them as lists are used to store values
list_1=[1,2,3]
list2=[1]
print(list_1+list2)

[1, 2, 3, 1]


In [9]:
#Contrary to lists arrays are used to perform mathematical operations
array_a+2

array([[3, 4, 5],
       [6, 7, 8]])

In [11]:
array_b+2

array([11,  5,  4])

In [19]:
print(array_b+array_a[0])


[10  5  5]


In [27]:
print(array_b+array_a[1])

[13  8  8]


In [17]:
print(array_a+array_b[0])


[[10 11 12]
 [13 14 15]]


In [21]:
print(array_a+array_b)

[[10  5  5]
 [13  8  8]]
