In [1]:
import numpy as np
matrix_a=np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_a

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [3]:
np.histogram(matrix_a)

(array([3, 2, 1, 3, 1, 1, 2, 0, 1, 1]),
 array([0. , 0.9, 1.8, 2.7, 3.6, 4.5, 5.4, 6.3, 7.2, 8.1, 9. ]))

In [5]:
np.histogram(matrix_a)[0]

array([3, 2, 1, 3, 1, 1, 2, 0, 1, 1])

In [7]:
np.histogram(matrix_a)[1]

array([0. , 0.9, 1.8, 2.7, 3.6, 4.5, 5.4, 6.3, 7.2, 8.1, 9. ])

In [9]:
np.histogram(matrix_a,bins=5)

(array([5, 4, 2, 2, 2]), array([0. , 1.8, 3.6, 5.4, 7.2, 9. ]))

In [19]:
pip install matplotlib --upgrade

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 1.5 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.7/13.7 MB 1.2 MB/s eta 0:00:0000:0100:01m
  Attempting uninstall: numpy
    Found existing installation: numpy 2.1.0
    Uninstalling numpy-2.1.0:
      Successfully uninstalled numpy-2.1.0
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.8.4
    Uninstalling matplotlib-3.8.4:
      Successfully uninstalled matplotlib-3.8.4
Note: you may need to restart the kernel to use updated packages.


In [28]:
import matplotlib.pyplot as plt
plt.hist(matrix_a.flat,np.histogram(matrix_a)[1])
plt.show()


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/harshalrathod/anaconda3/lib/python3.12/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/harshalrathod/anaconda3/lib/python3.12/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/Users/harshalrathod/anaconda3/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 701, in start
    self.io_loop.star

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/Users/harshalrathod/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/ml/q9fr3xdd28x7_k12s7w43pg80000gn/T/ipykernel_30244/1049163850.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "/Users/harshalrathod/anaconda3/lib/python3.12/site-packages/matplotlib/__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/Users/harshalrathod/anaconda3/lib/python3.12/site-packages/matplotlib/rcsetup.py", line 28, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/Users/harshalrathod/anaconda3/lib/python3.12/site-packages/matplotlib/colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/Users/harshalrathod/anaconda3/lib/python3.12/site-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib

In [30]:
matrix_a

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [32]:
#The 1-array represents the bin edges for x nd y axes and the 2-array represents the density for every x and y co-ordinate
np.histogram2d(matrix_a[0],matrix_a[1],bins=4)

(array([[0., 0., 2., 0.],
        [1., 0., 0., 1.],
        [0., 0., 0., 0.],
        [1., 0., 0., 0.]]),
 array([0.  , 0.75, 1.5 , 2.25, 3.  ]),
 array([2.  , 3.75, 5.5 , 7.25, 9.  ]))

In [34]:
#multi dimensional histogram
np.histogramdd(matrix_a.transpose(),bins=4)

(array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 1., 1., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 1., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]),
 [array([0.  , 0.75, 1.5 , 2.25, 3.  ]),
  array([2.  , 3.75, 5.5 , 7.25, 9.  ]),
  array([0., 2., 4., 6., 8.])])