In [1]:
import numpy as np


In [5]:
matrix_A=np.array([[1,2,3,8,6],[7,2,5,1,0],[4,1,2,3,6]])
matrix_A

array([[1, 2, 3, 8, 6],
       [7, 2, 5, 1, 0],
       [4, 1, 2, 3, 6]])

In [9]:
array_0_like=np.zeros_like(matrix_A)
array_0_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [16]:
array_empty_like=np.empty_like(matrix_A)
array_empty_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])