In [1]:
import numpy as np

In [13]:
matrix_A=np.array([[1,2,3,6],[0,1,4,7],[5,1,8,3]])
matrix_A

array([[1, 2, 3, 6],
       [0, 1, 4, 7],
       [5, 1, 8, 3]])

In [15]:
np.mean(matrix_A)

np.float64(3.4166666666666665)

In [17]:
np.mean(matrix_A[0])

np.float64(3.0)

In [19]:
np.mean(matrix_A[:,0])

np.float64(2.0)

In [21]:
np.mean(matrix_A,axis=0)

array([2.        , 1.33333333, 5.        , 5.33333333])

In [23]:
np.mean(matrix_A,axis=1)

array([3.  , 3.  , 4.25])

In [25]:
np.mean(matrix_A,axis=1,dtype='int64')

array([3, 3, 4])