In [1]:
import numpy as np

In [3]:
matrix_A=np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [5]:
np.min(matrix_A)

np.int64(0)

In [9]:
np.min(matrix_A[1])

np.int64(2)

In [13]:
#Exactly same as the min function
np.amin(matrix_A)

np.int64(0)

In [15]:
#Returns the arrays of the minimum values between 1st and 2nd row
np.minimum(matrix_A[0],matrix_A[1])

array([1, 0, 0, 2, 1])

In [17]:
#when we are using reduce we are essentially passing all the rows as the arguements the minimum value of the each corresponding position of every column will be returned as an array.
np.minimum.reduce(matrix_A)

array([1, 0, 0, 2, 0])

In [21]:
np.min(matrix_A,axis=0)

array([1, 0, 0, 2, 0])