In [1]:
import numpy as np

In [7]:
lending_compy=np.loadtxt("Lending-company-Numeric.csv",delimiter=',')

In [9]:
lending_compy

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [13]:
np.isnan(lending_compy)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [15]:
np.isnan(lending_compy).sum()

np.int64(0)

In [21]:
lending_compy_nan=np.genfromtxt("Lending-company-Numeric-NAN.csv",delimiter=';')

In [23]:
lending_compy_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [25]:
np.isnan(lending_compy_nan)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [27]:
np.isnan(lending_compy_nan).sum()

np.int64(260)

In [29]:
np.nanmax(lending_compy_nan)

np.float64(64001.0)

In [31]:
temp_fill=np.nanmax(lending_compy_nan)+1
lending_compy_nan=np.genfromtxt("Lending-company-Numeric-NAN.csv",delimiter=';',filling_values=temp_fill)

In [35]:
np.isnan(lending_compy_nan)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [37]:
np.isnan(lending_compy_nan).sum()

np.int64(0)