In [1]:
import numpy as np

In [3]:
lending_co_data_NAN=np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';')
lending_co_data_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [7]:
lending_co_data_NAN=np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',skip_header=2)
lending_co_data_NAN

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [9]:
lending_co_data_NAN=np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',skip_footer=2)
lending_co_data_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [13]:
lending_co_data_NAN=np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',usecols=(0))
lending_co_data_NAN

array([2000., 2000., 1000., ...,   nan, 1000., 2000.])

In [15]:
lending_co_data_NAN=np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',usecols=(0,1,5))
lending_co_data_NAN

array([[ 2000.,    40., 13621.],
       [ 2000.,    40., 15041.],
       [ 1000.,    40., 15340.],
       ...,
       [   nan,    40., 16600.],
       [ 1000.,    40., 15600.],
       [ 2000.,    40., 16600.]])

In [31]:
lending_co_data_NAN1,lending_co_data_NAN2,lending_co_data_NAN6=np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',usecols=(0,1,5),unpack=True)
print(lending_co_data_NAN1)
print(lending_co_data_NAN2)
print(lending_co_data_NAN6)

[2000. 2000. 1000. ...   nan 1000. 2000.]
[40. 40. 40. ... 40. 40. 40.]
[13621. 15041. 15340. ... 16600. 15600. 16600.]


In [33]:
lending_co_data_NAN6,lending_co_data_NAN2,lending_co_data_NAN1=np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',usecols=(5,1,0),unpack=True)


In [35]:
print(lending_co_data_NAN6)
print(lending_co_data_NAN2)
print(lending_co_data_NAN1)

[13621. 15041. 15340. ... 16600. 15600. 16600.]
[40. 40. 40. ... 40. 40. 40.]
[2000. 2000. 1000. ...   nan 1000. 2000.]
