In [1]:
import numpy as np

In [3]:
array_a=np.array([1,2,3])
array_a

array([1, 2, 3])

In [5]:
array_b=np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [9]:
matrix_c=np.array([[1,2,3],[4,5,6]])
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
#BroadCasting
print(np.add(array_a,matrix_c))

[[2 4 6]
 [5 7 9]]


In [17]:
print(np.add(array_b,matrix_c))

[[2 3 4]
 [6 7 8]]


In [23]:
#TypeCasting
np.add(array_a,matrix_c,dtype='str')


array([['11', '22', '33'],
       ['14', '25', '36']], dtype='<U42')

In [27]:
#Running over an axis , axis=0 is used for finding mean along the column
print(np.mean(matrix_c,axis=0)) 

[2.5 3.5 4.5]


In [29]:
#axis=1 is used for finding, axis=1 is used for finding mean along the row
print(np.mean(matrix_c,axis=1))

[2. 5.]
