In [1]:
import numpy as np

In [3]:
lending_co_data_numeric_data1=np.loadtxt('Lending-Company-Numeric-Data.csv',delimiter=',')
lending_co_data_numeric_data1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [5]:
lending_co_data_numeric_data2=np.genfromtxt('Lending-Company-Numeric-Data.csv',delimiter=',')
lending_co_data_numeric_data2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [11]:
np.array_equal(lending_co_data_numeric_data1,lending_co_data_numeric_data2)


True

In [23]:
#Throws error because it gets a symbol which is a string datatype and it cannot convert it to float 
lending_co_data_numeric_NAN=np.loadtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';')
lending_co_data_numeric_NAN

ValueError: could not convert string '' to float64 at row 11, column 4.

In [25]:
#gen from txt deals with illformatted data well which is useful when we deal with data not collected ourselves
lending_co_data_numeric_NAN=np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';')
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [27]:
#other way to display the data is convert all the values to a str datatype , not useful when doing mathematical operations (which we generally not our objective)
lending_co_data_numeric_NAN=np.loadtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',dtype='str')
lending_co_data_numeric_NAN

array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']], dtype='<U5')