In [5]:
import numpy as np
matrix_A=np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [7]:
#returns the difference between the maximum and the minimum values of the matrix
np.ptp(matrix_A)

np.int64(9)

In [9]:
np.ptp(matrix_A[0])

np.int64(3)

In [11]:
np.ptp(matrix_A,axis=0)

array([3, 6, 6, 6, 9])

In [13]:
np.ptp(matrix_A,axis=1)


array([3, 7, 8])

In [27]:
np.sort(matrix_A,axis=None)

array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 8, 9])

In [29]:
np.percentile(matrix_A,60)

np.float64(3.4000000000000004)

In [35]:
np.percentile(matrix_A,70)

np.float64(4.799999999999999)

In [37]:
np.quantile(matrix_A,.7)

np.float64(4.799999999999999)