In [3]:
import numpy as np

In [5]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [13]:
#creates a generator object from the genertor class 
random_array=gen(pcg())
random_array.normal()

-0.9741790569354726

In [19]:
#if we input a size then the randomly generated array will have that no of elements 
random_array.normal(size=5)

array([-1.18563621, -0.88212221,  1.06508819, -0.16158707,  1.02626152])

In [21]:
#if we input size as a tuple the shape of the array would be the size entered
random_array.normal(size=(3,3))

array([[-1.80993905, -0.52402902, -0.2344765 ],
       [-0.84323478,  0.81365066, -1.19248701],
       [-1.03631962,  0.16912768,  0.80986271]])

In [32]:
#if we assign a seed value then we would have the same randomly generated values eveytime 
ramdom_array=gen(pcg(seed=5))
ramdom_array.normal(size=(3,3))

array([[-0.80193143, -1.324359  , -0.24836162],
       [ 0.42044524,  1.13604653,  0.1097064 ],
       [-0.55264732, -0.78478036,  0.74874577]])

In [36]:
#The seed only lasts for one execution and is hence reset in this cell.
ramdom_array.normal(size=(3,3))

array([[ 1.63478304,  0.27276878, -1.23332866],
       [-0.95826521,  1.60001909,  0.20288244],
       [-1.73213484, -0.08369619, -1.16322597]])

In [38]:
#choice function chooses from given values
random_array.choice([1,2,3,4,5],size=(3,3))

array([[5, 4, 2],
       [1, 4, 4],
       [5, 5, 3]])

In [42]:
#we can also assign 
random_array.choice([1,2,3,4,5],p=[0.1,0.1,0.1,0.1,0.6],size=(3,3))

array([[5, 5, 4],
       [5, 5, 5],
       [5, 2, 5]])