In [1]:
import numpy as np
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [9]:
array_rg=gen(pcg(seed=5))
array_rg.normal(size=(3,3))

array([[-0.80193143, -1.324359  , -0.24836162],
       [ 0.42044524,  1.13604653,  0.1097064 ],
       [-0.55264732, -0.78478036,  0.74874577]])

In [13]:
#Randomly generates integers for the said given range
array_rg.integers(10,size=(3,3))

array([[1, 9, 1],
       [6, 7, 2],
       [2, 4, 2]])

In [21]:
#we can also specify the low and high values between which the integers function will assign integers
array_rg.integers(low=2,high=10,size=(3,3))

array([[8, 2, 5],
       [7, 5, 7],
       [7, 7, 2]])

In [25]:
#Random function assigns probabilities which are always between 0 and 1
array_rg.random(size=(3,3))

array([[0.01851722, 0.70749557, 0.00119968],
       [0.50336397, 0.43666705, 0.20325284],
       [0.32494264, 0.80621533, 0.31645209]])