In [11]:
import numpy as np
company_data_numeric=np.loadtxt("Lending-company-Numeric.csv",delimiter=",")[:8]
company_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [19]:
#shuffles the data in place 
np.random.shuffle(company_data_numeric)

In [21]:
company_data_numeric

array([[ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.]])

In [23]:
import numpy as np
company_data_numeric=np.loadtxt("Lending-company-Numeric.csv",delimiter=",")
company_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [25]:
np.random.shuffle(company_data_numeric)

In [27]:
company_data_numeric

array([[ 1000.,    35.,   365.,  2250.,  3475.,  8065.],
       [ 1000.,    40.,   365.,  2500.,  3580., 15600.],
       [ 4000.,    50.,   365.,  6350.,  7050., 22250.],
       ...,
       [ 2000.,    40.,   365.,  2861.,  4361., 16600.],
       [ 4000.,    50.,   365.,  5250.,  6650., 22250.],
       [ 2000.,    40.,   365.,  3401.,  4321., 13121.]])

In [29]:
from numpy.random import shuffle

In [31]:
shuffle(company_data_numeric)

In [33]:
company_data_numeric

array([[ 1000.,    40.,   365.,  3100.,  3700., 12720.],
       [ 2000.,    50.,   365.,  3501.,  4651., 16348.],
       [ 2000.,    40.,   365.,  3561.,  5253., 16323.],
       ...,
       [ 1000.,    50.,   365., -2450., -2000.,  1500.],
       [ 4000.,    50.,   365.,  6250.,  7250., 22250.],
       [ 2000.,    40.,   365.,  3501.,  5001., 16371.]])

In [35]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [49]:
array_RG=gen(pcg())
array_RG.shuffle(company_data_numeric)
company_data_numeric

array([[ 2000.,    40.,   365.,  4600.,  5800., 16600.],
       [ 2000.,    50.,   365.,  4501.,  7001., 20250.],
       [ 4000.,    50.,   365.,  5600.,  6800., 18300.],
       ...,
       [ 4000.,    50.,   365.,  6000.,  8250., 21250.],
       [ 1000.,    50.,   365.,   500.,  2200., 14950.],
       [ 2000.,    40.,   365.,  3160.,  4480., 16380.]])