In [1]:
import numpy as np

In [3]:
matrix=np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [7]:
#Stepwise Slicing
# ':' has the default value of 1 hence there doesn't need to be its mention. It is to ensure we do not skip over any unnecessary rows and columns.
matrix[::,::]


array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [11]:
matrix[::2,::]

array([[1, 1, 1, 2, 0],
       [4, 5, 3, 8, 0]])

In [9]:
matrix[::2,::2]

array([[1, 1, 0],
       [4, 3, 0]])

In [13]:
matrix[::-1,::]

array([[4, 5, 3, 8, 0],
       [3, 6, 6, 7, 4],
       [1, 1, 1, 2, 0]])

In [15]:
matrix[::,::-2]

array([[0, 1, 1],
       [4, 6, 3],
       [0, 3, 4]])

In [19]:
matrix[::-1,::2]

array([[4, 3, 0],
       [3, 6, 4],
       [1, 1, 0]])

In [23]:
#Conditional Slicing
matrix[:] > 2
#Returns true for all values that are greater than 2

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [25]:
matrix[matrix[:]>2]

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [27]:
matrix[matrix[:]<2]

array([1, 1, 1, 0, 0])

In [29]:
matrix[matrix[:]>=2]

array([2, 3, 6, 6, 7, 4, 4, 5, 3, 8])

In [37]:
matrix[(matrix[:]>4) & (matrix[:]%2==0)]

array([6, 6, 8])

In [39]:
matrix[(matrix[:]>4) | (matrix[:]%2==0)]

array([2, 0, 6, 6, 7, 4, 4, 5, 8, 0])