In [37]:
import numpy as np
lending_co_numeric=np.loadtxt("Lending-Company-Numeric-Data.csv",delimiter=",")
lending_co_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [39]:
lending_co_numeric_NAN=np.genfromtxt("Lending-company-Numeric-Data-NAN.csv",delimiter=";")
lending_co_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [41]:
temporary_fill=np.nanmax(lending_co_numeric_NAN)+1
temp_mean=np.nanmean(lending_co_numeric_NAN,axis=0).round(2)

lending_co_numeric_NAN=np.genfromtxt("Lending-company-Numeric-Data-NAN.csv",delimiter=";",filling_values=temporary_fill)

for i in range(lending_co_numeric_NAN.shape[1]):
    lending_co_numeric_NAN[:,i]=np.where(lending_co_numeric_NAN[:,i]==temporary_fill,temp_mean[i],lending_co_numeric_NAN[:,i])


In [43]:
lending_co_numeric_NAN

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [47]:
#It is similar to transposing a matrix here the columns are stacked as column values
np.stack((lending_co_numeric[:,0],lending_co_numeric[:,1]))

array([[2000., 2000., 1000., ..., 2000., 1000., 2000.],
       [  40.,   40.,   40., ...,   40.,   40.,   40.]])

In [ ]:
#The order can also be changed the first mentioned part of the array will come first 
np.stack((lending_co_numeric[:,1],lending_co_numeric[:,0]))

In [87]:
#We can also stack multiple elements
np.stack((lending_co_numeric[:,1],lending_co_numeric[:,0],lending_co_numeric[:,2]))

array([[  40.,   40.,   40., ...,   40.,   40.,   40.],
       [2000., 2000., 1000., ..., 2000., 1000., 2000.],
       [ 365.,  365.,  365., ...,  365.,  365.,  365.]])

In [ ]:
np.stack((lending_co_numeric[:,1],lending_co_numeric[:,0],))

In [51]:
#stacking columns side by side
np.stack((lending_co_numeric[:,0],lending_co_numeric[:,1]),axis=1)

array([[2000.,   40.],
       [2000.,   40.],
       [1000.,   40.],
       ...,
       [2000.,   40.],
       [1000.,   40.],
       [2000.,   40.]])

In [69]:
#Vertical stacking 
np.vstack((lending_co_numeric,lending_co_numeric_NAN))

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [71]:
#The stacks are one below the other
np.vstack((lending_co_numeric,lending_co_numeric_NAN)).shape

(2086, 6)

In [73]:
#The stacks are side by side (horizontally)
np.hstack((lending_co_numeric,lending_co_numeric_NAN))

array([[ 2000.,    40.,   365., ...,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365., ...,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365., ...,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365., ...,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365., ...,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365., ...,  4601.,  4601., 16600.]])

In [75]:
#Horizontal stack
np.hstack((lending_co_numeric,lending_co_numeric_NAN)).shape

(1043, 12)

In [77]:
#Depth stack (creates a 3-d stack)
np.dstack((lending_co_numeric,lending_co_numeric_NAN))

array([[[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 3121.  ,  3121.  ],
        [ 4241.  ,  4241.  ],
        [13621.  , 13621.  ]],

       [[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 3061.  ,  3061.  ],
        [ 4171.  ,  4171.  ],
        [15041.  , 15041.  ]],

       [[ 1000.  ,  1000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 2160.  ,  2160.  ],
        [ 3280.  ,  3280.  ],
        [15340.  , 15340.  ]],

       ...,

       [[ 2000.  ,  2250.25],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 4201.  ,  4201.  ],
        [ 5001.  ,  5001.  ],
        [16600.  , 16600.  ]],

       [[ 1000.  ,  1000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 2080.  ,  2080.  ],
        [ 3320.  ,  3320.  ],
        [15600.  , 15600.  ]],

       [[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  

In [81]:
#This means that we have 1043 6 by 2 arrays for each row of both the datasets
#The first index 1043 denotes the total no of the arrays , the second index 6 denotes 6 rows and the thrid index the two cols
#These indices can be used to access any value from these arrays 
np.dstack((lending_co_numeric,lending_co_numeric_NAN)).shape

(1043, 6, 2)

In [83]:
#displays the first row of both array
np.dstack((lending_co_numeric,lending_co_numeric_NAN))[0]

array([[ 2000.,  2000.],
       [   40.,    40.],
       [  365.,   365.],
       [ 3121.,  3121.],
       [ 4241.,  4241.],
       [13621., 13621.]])

In [85]:
#displays the first col of both arrays
np.dstack((lending_co_numeric,lending_co_numeric_NAN))[:,0]

array([[2000.  , 2000.  ],
       [2000.  , 2000.  ],
       [1000.  , 1000.  ],
       ...,
       [2000.  , 2250.25],
       [1000.  , 1000.  ],
       [2000.  , 2000.  ]])

In [89]:
#displayed all values of the first dataset lending_co_numeric
np.dstack((lending_co_numeric,lending_co_numeric_NAN))[0,:,0]

array([ 2000.,    40.,   365.,  3121.,  4241., 13621.])

In [95]:
#Stack always gives a higher dimension output for its input 
#The outputs for stack and dstack are equivalent for 1 and 2 d arrays
array_ex=np.array([[[1,2,3],[4,5,6],[6,3,2]],[[2,3,5],[7,1,3],[6,2,7]]])
array_ex2=array_ex*2

In [109]:
#For a 3-d array dstack returns a 3d array
np.dstack((array_ex,array_ex2)).shape


(2, 3, 6)

In [107]:
# For a 3-d array stack returns a 4d array
np.stack((array_ex,array_ex2),axis=-1).shape

(2, 3, 3, 2)