In [352]:
import numpy as np
np.set_printoptions(suppress=True,linewidth=100,precision=2)

In [354]:
raw_dat=np.genfromtxt("loan-data.csv",delimiter=";",encoding="latin1",skip_header=1)
raw_dat

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [355]:
temp_fill = np.nanmax(raw_dat)+1
temp_mean=np.nanmean(raw_dat,axis=0)
temp_mean

/var/folders/ml/q9fr3xdd28x7_k12s7w43pg80000gn/T/ipykernel_57711/2494869028.py:2: RuntimeWarning: Mean of empty slice
  temp_mean=np.nanmean(raw_dat,axis=0)


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [358]:
np.isnan(raw_dat).sum()

np.int64(88005)

In [360]:
string_cols=np.argwhere(np.isnan(temp_mean)).squeeze()
string_cols

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [362]:
numeric_cols=np.argwhere(np.isnan(temp_mean)==False).squeeze()
numeric_cols

array([ 0,  2,  4,  6,  7, 13])

In [364]:
loan_data_strings=np.genfromtxt("loan-data.csv",delimiter=";",encoding="latin1",skip_header=1,dtype=str,usecols=string_cols)
loan_data_strings

array([['May-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [366]:
loan_data_numeric=np.genfromtxt("loan-data.csv",delimiter=";",encoding="latin1",usecols=numeric_cols,filling_values=temp_fill)
loan_data_numeric

array([[68616520.  , 68616520.  , 68616520.  , 68616520.  , 68616520.  , 68616520.  ],
       [48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [368]:
temp_stats=np.array([temp_mean,np.nanmin(raw_dat,axis=0),np.nanmax(raw_dat,axis=0)])
                    

/var/folders/ml/q9fr3xdd28x7_k12s7w43pg80000gn/T/ipykernel_57711/4241603644.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats=np.array([temp_mean,np.nanmin(raw_dat,axis=0),np.nanmax(raw_dat,axis=0)])


In [370]:
full_header=np.genfromtxt("loan-data.csv",delimiter=";",encoding="latin1",skip_footer=raw_dat.shape[0],dtype=str)
full_header

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [372]:
string_header,numeric_header=full_header[string_cols],full_header[numeric_cols]

In [374]:
string_header

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [376]:
numeric_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [378]:
def checkpoint(file_name,checkpoint_header,checkpoint_data):
    np.savez(file_name,header=checkpoint_header,data=checkpoint_data)
    checkpoint_variable=np.load(file_name+".npz")
    return checkpoint_variable

In [380]:
checkpoint_test=checkpoint("checkpoint_test",string_header,loan_data_strings)
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [382]:
checkpoint_test['data']

array([['May-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [384]:
loan_data_strings

array([['May-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [386]:
loan_data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [388]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [398]:
loan_data_strings[:,0]=np.char.strip(loan_data_strings[:,0],"-15")
np.unique(loan_data_strings[:,0])


array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [402]:
months=np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])
months

array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      dtype='<U3')

In [404]:
for i in range(13):
    loan_data_strings[:,0]=np.where(loan_data_strings[:,0]==months[i],i,loan_data_strings[:,0])

DTypePromotionError: The DType <class 'numpy.dtypes._PyLongDType'> could not be promoted by <class 'numpy.dtypes.StrDType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes._PyLongDType'>, <class 'numpy.dtypes.StrDType'>)

In [406]:
loan_data_strings[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')