In [1]:
import numpy as np

lending_co_numeric=np.loadtxt("Lending-company-Numeric.csv",delimiter=",")
lending_co_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [3]:
#returns all values of the array once
np.unique(lending_co_numeric)

array([-2870., -2550., -2450., ..., 52751., 54625., 64001.])

In [11]:
#returns all values of the array once of the first column
np.unique(lending_co_numeric[:,1])

array([ 35.,  40.,  50., 125., 165.])

In [13]:
#returns all values of the array once of the first column along with the no of times it appears
np.unique(lending_co_numeric[:,1],return_counts=True)

(array([ 35.,  40.,  50., 125., 165.]), array([  4, 567, 451,  19,   2]))

In [15]:
#returns all values of the array once of the first column , the no of times it appears , the index of the first time it appears
np.unique(lending_co_numeric[:,1],return_counts=True,return_index=True)

(array([ 35.,  40.,  50., 125., 165.]),
 array([327,   0,   4,  19,  27]),
 array([  4, 567, 451,  19,   2]))