In [1]:
import numpy as np

In [3]:
matrix_a=np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_a

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [5]:
np.sort(matrix_a,axis=None)

array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 8, 9])

In [7]:
np.median(matrix_a)

np.float64(3.0)

In [9]:
np.mean(matrix_a)

np.float64(3.4)

In [37]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [69]:
array_rg=gen(pcg(seed=5))

arr_weights=np.array(array_rg.random(size=(3,5)))
arr_weights

array([[0.80500292, 0.80794079, 0.51532556, 0.28580138, 0.0539307 ],
       [0.38336888, 0.40847321, 0.04527519, 0.04875771, 0.99917612],
       [0.65236911, 0.2345102 , 0.43494755, 0.97418619, 0.89767761]])

In [73]:
np.average(matrix_a,weights=arr_weights)

np.float64(3.6518262839171576)

In [75]:
np.var(matrix_a)

np.float64(7.84)

In [77]:
np.std(matrix_a)

np.float64(2.8)

In [79]:
2.8**2

7.839999999999999